include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle prospector_adapter
    snippet: zmk-usb-logging
# there is no settingsreset (needed) for the XIAO
